name: packing
on:
  release:
    types: [created]
    branches:
      - master
jobs:
    build-project:
      name: build java application
      runs-on: ubuntu-latest
      permissions: 
        contents: read
        packages: write 
      steps:
        - name: checkout Code
          uses: actions/checkout@v2
        - name: setup java
          uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
        - name: caching dependences
          uses: actions/cache@v2
          with:
            path: dependencies/
            key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/lockfiles') }}
        - name: Validate Gradle wrapper
          uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
        - name: Publish package
          run: gradle publish
          env:
            GITHUB_TOKEN: ${{ secrets.DIEGO }}
