name: packing
on: [push]
jobs:
    run-shell-command:
      runs-on: ubuntu-latest
      steps:
          - name: echo string
            run: echo "hello world"
    build-project:
      name: build java application
      runs-on: ubuntu-latest
      steps:
        - name: checkout Code
          uses: actions/checkout@v2
        - name: setup java
          uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
        - name: caching dependences
          uses: actions/cache@v2
          with:
            path: path/to/dependencies
            key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/lockfiles') }}
        - name: build code
          run: ./gradlew build sonarqube --info
        - name: upload to artifacts
          uses: actions/upload-artifact@v2
          with:
            name: code-package
            path: out/
